name: ride_buddy_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1  
  firebase_storage: ^13.0.4 
  
  flutter:
    sdk: flutter
  
  geolocator: ^14.0.2        
  google_maps_flutter: ^2.6.0 
  

  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  flutter_background_service_ios: ^5.0.3
  flutter_local_notifications: ^19.5.0 
  
  flutter_dotenv: ^6.0.0   
  google_fonts: ^6.2.1       
  image_picker: ^1.1.2       
  intl: ^0.20.2            

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0      
  flutter_launcher_icons: ^0.14.4 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_4x4.png" 

flutter:
  uses-material-design: true

  assets:
    - assets/logo_ride.png
    - assets/capital.png
    - assets/revenue-growth.png
    - assets/relatorio-de-negocios.png
    - assets/99-logo.png
    - assets/ifood-logo.png
    - assets/uber-logo.png
    - assets/vrdrive-logo.png
    - assets/rappi-logo.png